#!/bin/bash

docker run -it --rm \
    --name my-running-script \
    --network coffee-machine_net \
    -v "$PWD":/usr/src/myapp \
    -w /usr/src/myapp \
    coffee-machine.php-cli php vendor/bin/phpunit $@
